<a href="https://colab.research.google.com/github/EimanAjmal/ML_Learning/blob/master/Python_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
 print("Hello World")

Hello World


In [2]:
a = 10
b = 3
print(a + b)   # 13
print(a - b)   # 7
print(a * b)   # 30
print(a / b)   # 3.333... (float division)
print(a // b)  # 3 (integer division)
print(a % b)   # 1 (remainder)

13
7
30
3.3333333333333335
3
1


In [4]:
marks = 75

if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 60:
    grade = "C"
else:
    grade = "F"

print(f"Grade: {grade}")

Grade: B


In [5]:
# for loop
for i in range(5):
    print(i)   # 0, 1, 2, 3, 4

# while loop
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4
0
1
2
3
4


In [6]:
fruits = ["apple", "banana", "mango"]
print(fruits[0])        # apple
fruits.append("orange") # add karo
print(len(fruits))      # 4 — length

for fruit in fruits:
    print(fruit)

apple
4
apple
banana
mango
orange


In [8]:
name = "Ahmed"          # string
age = 21                 # integer
gpa = 3.4                # float
is_student = True        # boolean

print(name, age, gpa, is_student)
print(type(age))

Ahmed 21 3.4 True
<class 'int'>


In [9]:
for number in range(1, 21):
    if number % 2 == 0:
        print(number, "(even)")
    else:
        print(number)

1
2 (even)
3
4 (even)
5
6 (even)
7
8 (even)
9
10 (even)
11
12 (even)
13
14 (even)
15
16 (even)
17
18 (even)
19
20 (even)


In [10]:
def greet(name):
    return f"Hello, {name}!"

print(greet("Ahmed"))   # Hello, Ahmed!
print(greet("Sara"))    # Hello, Sara!

Hello, Ahmed!
Hello, Sara!


In [12]:
def add_numbers(a, b=10):
    return a + b

print(add_numbers(5, 3))
print(add_numbers(5))

8
15


In [13]:
def is_even(number):
    if number % 2 == 0:
        return True
    else:
        return False

print(is_even(4))   # True
print(is_even(7))   # False

True
False


In [14]:
for i in range(3):
    for j in range(2):
        print(f"i={i}, j={j}")

i=0, j=0
i=0, j=1
i=1, j=0
i=1, j=1
i=2, j=0
i=2, j=1


In [15]:
for i in range(10):
    if i == 5:
        break
    print(i)

0
1
2
3
4


In [16]:
for i in range(10):
    if i % 2 == 0:
        continue
    print(i)

1
3
5
7
9


In [17]:
squares = []
for x in range(1, 6):
    squares.append(x * x)
print(squares)   # [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


In [18]:
squares = [x * x for x in range(1, 6)]
print(squares)   # [1, 4, 9, 16, 25]

[1, 4, 9, 16, 25]


In [19]:
even_numbers = [x for x in range(1, 21) if x % 2 == 0]
print(even_numbers)   # [2, 4, 6, ..., 20]

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))   # numpy.ndarray

# 2D array (matrix jaisa)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
arr = np.array([1, 2, 3, 4, 5])

print(arr + 10)      # [11 12 13 14 15]
print(arr * 2)       # [2 4 6 8 10]
print(arr > 3)        # [False False False True True]
arr = np.array([4, 8, 2, 10, 6])

print(arr.sum())     # 30 - total
print(arr.mean())    # 6.0 - average
print(arr.max())     # 10
print(arr.min())     # 2
print(arr.shape)     # (5,)
print(len(arr))      # 5
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])      # 10 (pehla element)
print(arr[-1])     # 50 (last element)
print(arr[1:4])    # [20 30 40]
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)   # 2 rows, 3 columns
print(reshaped)
# [[1 2 3]
#  [4 5 6]]

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
[11 12 13 14 15]
[ 2  4  6  8 10]
[False False False  True  True]
30
6.0
10
2
(5,)
5
10
50
[20 30 40]
[[1 2 3]
 [4 5 6]]
